/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "fs.pb-c.h"
void   create__init
                     (Create         *message)
{
  static Create init_value = CREATE__INIT;
  *message = init_value;
}
size_t create__get_packed_size
                     (const Create *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &create__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t create__pack
                     (const Create *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &create__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t create__pack_to_buffer
                     (const Create *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &create__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Create *
       create__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Create *)
     protobuf_c_message_unpack (&create__descriptor,
                                allocator, len, data);
}
void   create__free_unpacked
                     (Create *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &create__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   create_resp__init
                     (CreateResp         *message)
{
  static CreateResp init_value = CREATE_RESP__INIT;
  *message = init_value;
}
size_t create_resp__get_packed_size
                     (const CreateResp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &create_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t create_resp__pack
                     (const CreateResp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &create_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t create_resp__pack_to_buffer
                     (const CreateResp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &create_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CreateResp *
       create_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CreateResp *)
     protobuf_c_message_unpack (&create_resp__descriptor,
                                allocator, len, data);
}
void   create_resp__free_unpacked
                     (CreateResp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &create_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor create__field_descriptors[2] =
{
  {
    "path",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Create, path),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Create, mode),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned create__field_indices_by_name[] = {
  1,   /* field[1] = mode */
  0,   /* field[0] = path */
};
static const ProtobufCIntRange create__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor create__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Create",
  "Create",
  "Create",
  "",
  sizeof(Create),
  2,
  create__field_descriptors,
  create__field_indices_by_name,
  1,  create__number_ranges,
  (ProtobufCMessageInit) create__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor create_resp__field_descriptors[1] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CreateResp, result),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned create_resp__field_indices_by_name[] = {
  0,   /* field[0] = result */
};
static const ProtobufCIntRange create_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor create_resp__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "CreateResp",
  "CreateResp",
  "CreateResp",
  "",
  sizeof(CreateResp),
  1,
  create_resp__field_descriptors,
  create_resp__field_indices_by_name,
  1,  create_resp__number_ranges,
  (ProtobufCMessageInit) create_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor fsservice__method_descriptors[2] =
{
  { "ReplyToPing", &ping__descriptor, &ping__descriptor },
  { "CreateFile", &create__descriptor, &create_resp__descriptor },
};
const unsigned fsservice__method_indices_by_name[] = {
  1,        /* CreateFile */
  0         /* ReplyToPing */
};
const ProtobufCServiceDescriptor fsservice__descriptor =
{
  PROTOBUF_C_SERVICE_DESCRIPTOR_MAGIC,
  "FSService",
  "ReplyToPing",
  "FSService",
  "",
  2,
  fsservice__method_descriptors,
  fsservice__method_indices_by_name
};
void fsservice__reply_to_ping(ProtobufCService *service,
                              const Ping *input,
                              Ping_Closure closure,
                              void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &fsservice__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void fsservice__create_file(ProtobufCService *service,
                            const Create *input,
                            CreateResp_Closure closure,
                            void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &fsservice__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void fsservice__init (FSService_Service *service,
                      FSService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &fsservice__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
