CC = gcc
CCFLAGS = -g -pedantic -wall
SERVER_LIBS = 
CLIENT_LIBS = 

SERVER_EXEC = serverSNFS
CLIENT_EXEC = clientSNFS 
	
all: ${SERVER_EXEC} ${CLIENT_EXEC}

${SERVER_EXEC}:

${CLIENT_EXEC}:


clean:
	rm -f *.o
	rm ${SERVER_EXEC}
	rm ${CLIENT_EXEC}
