#pragma once

#define CREATE_MESSAGE 1
#define OPEN_MESSAGE 2
#define CLOSE_MESSAGE 3
#define TRUNCATE_MESSAGE 4
#define GETATTR_MESSAGE 5
#define READ_MESSAGE 6
#define WRITE_MESSAGE 7
#define OPENDIR_MESSAGE 8
#define READDIR_MESSAGE 9
#define RELEASEDIR_MESSAGE 10
#define MKDIR_MESSAGE 11

#define FILE_RESPONSE_MESSAGE 12
#define GETATTR_RESPONSE_MESSAGE 13
#define ERROR_RESPONSE_MESSAGE 14
